import {
    createGlobalTheme,
    createTheme,
    createThemeContract,
} from "@vanilla-extract/css";

/**
 * Primitive token values from the design system source.
 */
const primitives = {
    brand: {
        5: "#00102E",
        10: "#001847",
        20: "#002C72",
        30: "#0040A0",
        40: "#0056D1",
        50: "#3070EF",
        60: "#5A8CFF",
        70: "#88A9FF",
        80: "#B2C5FF",
        90: "#DAE2FF",
        95: "#EEF0FF",
    },
    neutral: {
        0: "#000000",
        5: "#0E0E0E",
        10: "#1F1F1F",
        20: "#343434",
        30: "#4D4D4D",
        40: "#666666",
        50: "#808080",
        60: "#999999",
        70: "#B2B2B2",
        80: "#CCCCCC",
        90: "#E6E6E6",
        95: "#F2F2F2",
        100: "#FFFFFF",
    },
    error: {
        10: "#3D0C0A",
        20: "#611A16",
        30: "#922821",
        40: "#C33620",
        50: "#D04D45",
        60: "#D66965",
        70: "#DE8B86",
        80: "#E6AAA9",
        90: "#F8CCCB",
        95: "#F9EDEB",
    },
    success: {
        10: "#175118",
        20: "#386336",
        30: "#409551",
        40: "#61C76C",
        50: "#73D580",
        60: "#88DC96",
        70: "#9FEAAB",
        80: "#B9E8C4",
        90: "#D5F3DC",
        95: "#E2F7E7",
    },
};

export const vars = createThemeContract({
    color: {
        brandBase: "",
        brandDark: "",
        brandLight: "",
        brandDarkest: "",
        appSidebarSurface: "",
        appSidebarSurfaceHover: "",
        appSidebarSurfaceActive: "",
        appSidebarBorder: "",
        appSidebarOnSurface: "",
        appSidebarOnSurfaceMuted: "",
        surfacePrimary: "",
        surfaceSecondary: "",
        surfaceTertiary: "",
        surfaceBorder: "",
        surfaceInvert: "",
        surfaceOverlay: "",
        onSurfacePrimary: "",
        onSurfaceSecondary: "",
        onSurfaceTertiary: "",
        onSurfaceInvert: "",
        surfaceError: "",
        onSurfaceError: "",
        surfaceSuccess: "",
        onSurfaceSuccess: "",
        scrollbarTrough: "",
        scrollbarBar: "",
        scrollbarBarHover: "",
        scrollbarArrow: "",
        scrollbarArrowHover: "",
    },
    button: {
        primary: {
            surface: "",
            surfaceHover: "",
            surfaceActive: "",
            onSurface: "",
            border: "",
        },
        secondary: {
            surface: "",
            surfaceHover: "",
            surfaceActive: "",
            onSurface: "",
            border: "",
            borderHover: "",
        },
        tertiary: {
            surfaceHover: "",
            surfaceActive: "",
            onSurface: "",
            onSurfaceHover: "",
        },
    },
    kbd: {
        surface: "",
        onSurface: "",
        border: "",
    },
    toggleGroup: {
        surface: "",
        itemSelectedSurface: "",
        itemSelectedBorder: "",
        itemSelectedOnSurface: "",
        itemUnselectedOnSurface: "",
    },
    typography: {
        fontFamily: "",
        h1: { fontSize: "", fontWeight: "", lineHeight: "" },
        h2: { fontSize: "", fontWeight: "", lineHeight: "" },
        h3: { fontSize: "", fontWeight: "", lineHeight: "" },
        h4: { fontSize: "", fontWeight: "", lineHeight: "" },
        h5: { fontSize: "", fontWeight: "", lineHeight: "" },
        bodyULB: { fontSize: "", fontWeight: "", lineHeight: "" },
        bodyNormal: { fontSize: "", fontWeight: "", lineHeight: "" },
        bodySmall: { fontSize: "", fontWeight: "", lineHeight: "" },
        bodySmallest: { fontSize: "", fontWeight: "", lineHeight: "" },
        label: { fontSize: "", fontWeight: "", lineHeight: "" },
    },
    spacing: {
        none: "",
        xs: "",
        sm: "",
        md: "",
        lg: "",
        xl: "",
    },
    breakpoints: {
        xs: "",
        sm: "",
        md: "",
        lg: "",
        xl: "",
    },
    shadow: {
        small: "",
        medium: "",
        large: "",
    },
    border: {
        width: {
            thin: "",
            thick: "",
        },
        radius: {
            xs: "",
            sm: "",
            md: "",
            lg: "",
            xl: "",
            full: "",
        },
    },
});

const commonTokens = {
    typography: {
        fontFamily: "'Atkinson Hyperlegible', system-ui, sans-serif",
        h1: { fontSize: "3rem", fontWeight: "700", lineHeight: "1" },
        h2: { fontSize: "2.25rem", fontWeight: "400", lineHeight: "1.1" },
        h3: { fontSize: "1.5rem", fontWeight: "700", lineHeight: "1.2" },
        h4: { fontSize: "1.25rem", fontWeight: "700", lineHeight: "1.2" },
        h5: { fontSize: "1.25rem", fontWeight: "700", lineHeight: "1.2" },
        bodyULB: { fontSize: "1.25rem", fontWeight: "400", lineHeight: "2.4" },
        bodyNormal: {
            fontSize: "1.25rem",
            fontWeight: "400",
            lineHeight: "1.6",
        },
        bodySmall: { fontSize: "1rem", fontWeight: "400", lineHeight: "1.5" },
        bodySmallest: {
            fontSize: "0.75rem",
            fontWeight: "400",
            lineHeight: "1.5",
        },
        label: { fontSize: "1.25rem", fontWeight: "400", lineHeight: "1.2" },
    },
    spacing: {
        none: "0",
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "3rem",
        xl: "5rem",
    },
    breakpoints: {
        xs: "0em",
        sm: "36em",
        md: "48em",
        lg: "62em",
        xl: "75em",
    },
    border: {
        width: {
            thin: "1px",
            thick: "2px",
        },
        radius: {
            xs: "2px",
            sm: "4px",
            md: "8px",
            lg: "12px",
            xl: "16px",
            full: "9999px",
        },
    },
};

export const dsVars = vars;

const lightValues = {
    ...commonTokens,
    color: {
        brandBase: primitives.brand[40],
        brandDark: primitives.brand[30],
        brandLight: primitives.brand[95],
        brandDarkest: primitives.brand[10],
        appSidebarSurface: primitives.brand[10],
        appSidebarSurfaceHover: "color-mix(in srgb, #ffffff 8%, transparent)",
        appSidebarSurfaceActive: "color-mix(in srgb, #ffffff 12%, transparent)",
        appSidebarBorder: "color-mix(in srgb, white 8%, transparent)",
        appSidebarOnSurface: primitives.neutral[100],
        appSidebarOnSurfaceMuted: "color-mix(in srgb, white 64%, transparent)",
        surfacePrimary: primitives.neutral[100],
        surfaceSecondary: primitives.neutral[95],
        surfaceTertiary: primitives.neutral[90],
        surfaceBorder: primitives.neutral[90],
        surfaceInvert: primitives.neutral[5],
        surfaceOverlay: "rgba(31, 31, 31, 0.6)",
        onSurfacePrimary: primitives.neutral[5],
        onSurfaceSecondary: primitives.neutral[20],
        onSurfaceTertiary: primitives.neutral[60],
        onSurfaceInvert: primitives.neutral[100],
        surfaceError: primitives.error[95],
        onSurfaceError: primitives.error[40],
        surfaceSuccess: primitives.success[95],
        onSurfaceSuccess: primitives.success[40],
        scrollbarTrough: primitives.neutral[90],
        scrollbarBar: primitives.neutral[30],
        scrollbarBarHover: primitives.neutral[20],
        scrollbarArrow: primitives.neutral[95],
        scrollbarArrowHover: primitives.neutral[90],
    },
    button: {
        primary: {
            surface: primitives.brand[40],
            surfaceHover: primitives.brand[30],
            surfaceActive: primitives.brand[20],
            onSurface: primitives.neutral[100],
            border: primitives.brand[40],
        },
        secondary: {
            surface: "transparent",
            surfaceHover: primitives.neutral[95],
            surfaceActive: primitives.neutral[90],
            onSurface: primitives.neutral[5],
            border: primitives.neutral[90],
            borderHover: primitives.neutral[80],
        },
        tertiary: {
            surfaceHover: primitives.neutral[95],
            surfaceActive: primitives.neutral[90],
            onSurface: primitives.neutral[20],
            onSurfaceHover: primitives.neutral[5],
        },
    },
    kbd: {
        surface: "#F4F8FB",
        onSurface: "rgba(15, 47, 76, 0.8)",
        border: primitives.neutral[90],
    },
    toggleGroup: {
        surface: "#F4F8FB",
        itemSelectedSurface: primitives.neutral[100],
        itemSelectedBorder: primitives.brand[40],
        itemSelectedOnSurface: primitives.brand[40],
        itemUnselectedOnSurface: "rgba(15, 47, 76, 0.8)",
    },
    shadow: {
        small: "0px 1px 2px 0px rgba(31, 31, 31, 0.12)",
        medium: "0px 2px 4px 0px rgba(31, 31, 31, 0.16), 0px 1px 3px 0px rgba(31, 31, 31, 0.1)",
        large: "0px 4px 8px 0px rgba(31, 31, 31, 0.2), 0px 2px 4px 0px rgba(31, 31, 31, 0.12)",
    },
};

const darkValues = {
    ...commonTokens,
    color: {
        brandBase: primitives.brand[70],
        brandDark: primitives.brand[70],
        brandLight: primitives.brand[5],
        brandDarkest: primitives.brand[80],
        appSidebarSurface: primitives.brand[10],
        appSidebarSurfaceHover: "color-mix(in srgb, #ffffff 8%, transparent)",
        appSidebarSurfaceActive: "color-mix(in srgb, #ffffff 12%, transparent)",
        appSidebarBorder: "color-mix(in srgb, white 8%, transparent)",
        appSidebarOnSurface: primitives.neutral[100],
        appSidebarOnSurfaceMuted: "color-mix(in srgb, white 64%, transparent)",
        surfacePrimary: primitives.neutral[20],
        surfaceSecondary: primitives.neutral[10],
        surfaceTertiary: primitives.neutral[5],
        surfaceBorder: primitives.neutral[5],
        surfaceInvert: primitives.neutral[90],
        surfaceOverlay: "rgba(31, 31, 31, 0.8)",
        onSurfacePrimary: primitives.neutral[90],
        onSurfaceSecondary: primitives.neutral[80],
        onSurfaceTertiary: primitives.neutral[50],
        onSurfaceInvert: primitives.neutral[10],
        surfaceError: primitives.error[20],
        onSurfaceError: primitives.error[80],
        surfaceSuccess: primitives.success[20],
        onSurfaceSuccess: primitives.success[80],
        scrollbarTrough: primitives.neutral[10],
        scrollbarBar: primitives.neutral[80],
        scrollbarBarHover: primitives.neutral[90],
        scrollbarArrow: primitives.neutral[20],
        scrollbarArrowHover: primitives.neutral[10],
    },
    button: {
        primary: {
            surface: primitives.brand[70],
            surfaceHover: primitives.brand[80],
            surfaceActive: primitives.brand[90],
            onSurface: primitives.neutral[10],
            border: primitives.brand[70],
        },
        secondary: {
            surface: "transparent",
            surfaceHover: primitives.neutral[10],
            surfaceActive: primitives.neutral[5],
            onSurface: primitives.neutral[90],
            border: primitives.neutral[5],
            borderHover: primitives.neutral[0],
        },
        tertiary: {
            surfaceHover: primitives.neutral[10],
            surfaceActive: primitives.neutral[5],
            onSurface: primitives.neutral[80],
            onSurfaceHover: primitives.neutral[95],
        },
    },
    kbd: {
        surface: primitives.neutral[10],
        onSurface: primitives.neutral[80],
        border: primitives.neutral[5],
    },
    toggleGroup: {
        surface: primitives.neutral[5],
        itemSelectedSurface: primitives.neutral[20],
        itemSelectedBorder: primitives.brand[70],
        itemSelectedOnSurface: primitives.brand[70],
        itemUnselectedOnSurface: primitives.neutral[80],
    },
    shadow: {
        small: "0px 1px 2px 0px rgba(0, 0, 0, 0.4)",
        medium: "0px 2px 4px 0px rgba(0, 0, 0, 0.5)",
        large: "0px 4px 8px 0px rgba(0, 0, 0, 0.6)",
    },
};

createGlobalTheme(":root", vars, lightValues);

export const lightThemeClass = createTheme(vars, lightValues);
export const darkThemeClass = createTheme(vars, darkValues);
