import { defineConfig, devices } from "@playwright/test";

const requestedWorkers = process.env.PLAYWRIGHT_WORKERS
  ? Number(process.env.PLAYWRIGHT_WORKERS)
  : null;
const useLocalParallelBrowsers =
  !process.env.CI && requestedWorkers !== null && requestedWorkers > 1;

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  /* Run tests in files in parallel */
  fullyParallel: !process.env.CI,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Keep local default at one worker for reliability in this macOS environment.
   * Parallelism can still be requested explicitly via PLAYWRIGHT_WORKERS.
   */
  workers: process.env.PLAYWRIGHT_WORKERS
    ? (requestedWorkers ?? undefined)
    : process.env.CI
      ? 2
      : 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters
   * Can be configured via the PLAYWRIGHT_REPORTER environment variable.
   * Default to 'list' so HTML report is not generated by default.
   */
  reporter: process.env.PLAYWRIGHT_REPORTER ?? "list",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('')`. */
    baseURL: process.env.BASE_URL ?? "http://localhost:5175",

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      // Local dev: use system Chrome so Playwright doesn't require bundled browser downloads.
      // For local parallel runs, fall back to Playwright-managed Chromium because
      // concurrent system-Chrome launches are unstable in this environment.
      use: process.env.CI
        ? { ...devices["Desktop Chrome"] }
        : useLocalParallelBrowsers
          ? { ...devices["Desktop Chrome"] }
          : { ...devices["Desktop Chrome"], channel: "chrome" },
    },

    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },
    // !: NOTE: NO WEBKIT. AUTOMATED BROWSERS RUN AS PRIVATE, AND OPFS does not work in private browsers for webkit.

    // {
    //   name: "webkit",
    //   use: {...devices["Desktop Safari"]},
    // },

    /* Test against mobile viewports. */
    {
      name: "Mobile Chrome",
      use: process.env.CI
        ? { ...devices["Pixel 5"] }
        : useLocalParallelBrowsers
          ? { ...devices["Pixel 5"] }
          : { ...devices["Pixel 5"], channel: "chrome" },
    },
    // {
    //   name: "Mobile Safari",
    //   use: {...devices["iPhone 12"]},
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  webServer: process.env.CI
    ? {
        command: "pnpm run preview",
        url: "http://localhost:4173",
        reuseExistingServer: !process.env.CI,
      }
    : undefined,
});
