import os from "node:os";
import { defineConfig, devices } from "@playwright/test";

const requestedWorkers = process.env.PLAYWRIGHT_WORKERS
  ? Number(process.env.PLAYWRIGHT_WORKERS)
  : null;
// `E2E_ALL_BROWSERS=1` enables firefox + mobile; `E2E_MOBILE=1` enables only mobile.
// Mobile is opt-in everywhere (including CI) because feature parity with desktop
// is a work in progress — the mobile layout still uses surfaces (drawer/hamburger
// menus, etc.) that the existing test helpers don't drive. CI runs chromium +
// firefox by default; turn mobile on per-run with E2E_MOBILE=1 once a spec gains
// real mobile coverage (via `test.use(devices['Pixel 5'])`).
const runFirefox = !!process.env.CI || !!process.env.E2E_ALL_BROWSERS;
const runMobile = !!process.env.E2E_ALL_BROWSERS || !!process.env.E2E_MOBILE;
// Default local parallelism: half of available cores (min 2). Uses Playwright-managed
// Chromium below — concurrent launches of the system Chrome channel are unstable.
const defaultLocalWorkers = Math.max(2, Math.floor(os.cpus().length / 2));

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  workers: requestedWorkers ?? (process.env.CI ? 2 : defaultLocalWorkers),
  /* Reporter to use. See https://playwright.dev/docs/test-reporters
   * Can be configured via the PLAYWRIGHT_REPORTER environment variable.
   * Default to 'list' so HTML report is not generated by default.
   */
  reporter: process.env.PLAYWRIGHT_REPORTER ?? "list",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('')`. */
    baseURL: process.env.BASE_URL ?? "http://localhost:5175",

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
  },

  /* Configure projects for major browsers.
   * Locally, only chromium runs by default. Use Playwright-managed Chromium
   * throughout — the system Chrome channel does not parallelize reliably.
   *   E2E_ALL_BROWSERS=1   → also run firefox and Mobile Chrome
   *   E2E_MOBILE=1         → also run Mobile Chrome
   * CI always runs all.
   */
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    ...(runFirefox
      ? [
          {
            name: "firefox",
            use: { ...devices["Desktop Firefox"] },
          },
        ]
      : []),
    // !: NOTE: NO WEBKIT. AUTOMATED BROWSERS RUN AS PRIVATE, AND OPFS does not work in private browsers for webkit.
    ...(runMobile
      ? [
          {
            name: "Mobile Chrome",
            use: { ...devices["Pixel 5"] },
          },
        ]
      : []),
    // {
    //   name: "Mobile Safari",
    //   use: {...devices["iPhone 12"]},
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests.
   * CI uses the built preview server; local attaches to a running `pnpm dev.web`
   * if one is up, otherwise starts it.
   */
  webServer: process.env.CI
    ? {
        command: "pnpm run preview",
        url: "http://localhost:4173",
        reuseExistingServer: false,
      }
    : {
        command: "pnpm dev.web",
        url: "http://localhost:5175",
        reuseExistingServer: true,
        timeout: 120_000,
      },
});
