export const canonicalBookMap: {
  [key: string]: { num: string; code: string; testament: string };
} = {
  // Old Testament
  GEN: { num: "01", code: "GEN", testament: "ot" },
  EXO: { num: "02", code: "EXO", testament: "ot" },
  LEV: { num: "03", code: "LEV", testament: "ot" },
  NUM: { num: "04", code: "NUM", testament: "ot" },
  DEU: { num: "05", code: "DEU", testament: "ot" },
  JOS: { num: "06", code: "JOS", testament: "ot" },
  JDG: { num: "07", code: "JDG", testament: "ot" },
  RUT: { num: "08", code: "RUT", testament: "ot" },
  "1SA": { num: "09", code: "1SA", testament: "ot" },
  "2SA": { num: "10", code: "2SA", testament: "ot" },
  "1KI": { num: "11", code: "1KI", testament: "ot" },
  "2KI": { num: "12", code: "2KI", testament: "ot" },
  "1CH": { num: "13", code: "1CH", testament: "ot" },
  "2CH": { num: "14", code: "2CH", testament: "ot" },
  EZR: { num: "15", code: "EZR", testament: "ot" },
  NEH: { num: "16", code: "NEH", testament: "ot" },
  EST: { num: "17", code: "EST", testament: "ot" },
  JOB: { num: "18", code: "JOB", testament: "ot" },
  PSA: { num: "19", code: "PSA", testament: "ot" },
  PRO: { num: "20", code: "PRO", testament: "ot" },
  ECC: { num: "21", code: "ECC", testament: "ot" },
  SNG: { num: "22", code: "SNG", testament: "ot" },
  ISA: { num: "23", code: "ISA", testament: "ot" },
  JER: { num: "24", code: "JER", testament: "ot" },
  LAM: { num: "25", code: "LAM", testament: "ot" },
  EZK: { num: "26", code: "EZK", testament: "ot" },
  DAN: { num: "27", code: "DAN", testament: "ot" },
  HOS: { num: "28", code: "HOS", testament: "ot" },
  JOL: { num: "29", code: "JOL", testament: "ot" },
  AMO: { num: "30", code: "AMO", testament: "ot" },
  OBA: { num: "31", code: "OBA", testament: "ot" },
  JON: { num: "32", code: "JON", testament: "ot" },
  MIC: { num: "33", code: "MIC", testament: "ot" },
  NAM: { num: "34", code: "NAM", testament: "ot" },
  HAB: { num: "35", code: "HAB", testament: "ot" },
  ZEP: { num: "36", code: "ZEP", testament: "ot" },
  HAG: { num: "37", code: "HAG", testament: "ot" },
  ZEC: { num: "38", code: "ZEC", testament: "ot" },
  MAL: { num: "39", code: "MAL", testament: "ot" },

  // New Testament
  MAT: { num: "41", code: "MAT", testament: "nt" },
  MRK: { num: "42", code: "MRK", testament: "nt" },
  LUK: { num: "43", code: "LUK", testament: "nt" },
  JHN: { num: "44", code: "JHN", testament: "nt" },
  ACT: { num: "45", code: "ACT", testament: "nt" },
  ROM: { num: "46", code: "ROM", testament: "nt" },
  "1CO": { num: "47", code: "1CO", testament: "nt" },
  "2CO": { num: "48", code: "2CO", testament: "nt" },
  GAL: { num: "49", code: "GAL", testament: "nt" },
  EPH: { num: "50", code: "EPH", testament: "nt" },
  PHP: { num: "51", code: "PHP", testament: "nt" },
  COL: { num: "52", code: "COL", testament: "nt" },
  "1TH": { num: "53", code: "1TH", testament: "nt" },
  "2TH": { num: "54", code: "2TH", testament: "nt" },
  "1TI": { num: "55", code: "1TI", testament: "nt" },
  "2TI": { num: "56", code: "2TI", testament: "nt" },
  TIT: { num: "57", code: "TIT", testament: "nt" },
  PHM: { num: "58", code: "PHM", testament: "nt" },
  HEB: { num: "59", code: "HEB", testament: "nt" },
  JAS: { num: "60", code: "JAS", testament: "nt" },
  "1PE": { num: "61", code: "1PE", testament: "nt" },
  "2PE": { num: "62", code: "2PE", testament: "nt" },
  "1JN": { num: "63", code: "1JN", testament: "nt" },
  "2JN": { num: "64", code: "2JN", testament: "nt" },
  "3JN": { num: "65", code: "3JN", testament: "nt" },
  JUD: { num: "66", code: "JUD", testament: "nt" },
  REV: { num: "67", code: "REV", testament: "nt" },
};
