use logos::Logos;
use once_cell::sync::Lazy;
use regex::Regex;
use serde::Serialize;
use std::collections::{HashMap, HashSet};

/// The primary Token enum for USFM, generated by `logos`.
/// This enum represents all possible lexical units in the USFM source.
/// The order is important: more specific regexes should come before
/// more general ones to resolve ambiguity.
#[derive(Logos, Debug, PartialEq, Eq, Clone, Copy, Hash, Serialize)]
pub enum TokenKind {
    // --- 1. Whitespace ---
    #[regex(r"(?:\r\n|\n)+", priority = 1000)]
    Nl,
    #[regex(r"[ \t]+", priority = 1000)]
    Ws,

    // --- 2. Attributes ---
    #[token("|")]
    Pipe,
    #[regex(r#"[a-zA-Z0-9\-_]+="(?:\\.|[^"\\])*""#)]
    AttrPair,

    // --- 3. Markers (Specific regexes first) ---
    // Table markers
    #[regex(r"\\thr[\d]+(?:-[\d]+)?")]
    Thr,
    #[regex(r"\\thc[\d]+(?:-[\d]+)?")]
    Thc,
    #[regex(r"\\th[\d]+(?:-[\d]+)?")]
    Th,
    #[regex(r"\\tcr[\d]+(?:-[\d]+)?")]
    Tcr,
    #[regex(r"\\tcc[\d]+(?:-[\d]+)?")]
    Tcc,
    #[regex(r"\\tc[\d]+(?:-[\d]+)?")]
    Tc,

    // Milestone markers
    #[regex(r"\\qt[1-5]?-s")]
    QtMilestoneStart,
    #[regex(r"\\qt[1-5]?-e")]
    QtMilestoneEnd,
    #[regex(r"\\ts-s")]
    TsMilestoneStart,
    #[regex(r"\\ts-e")]
    TsMilestoneEnd,
    #[regex(r"\\z[\w-]+\*")]
    ZMilestoneEnd,

    // Markers with optional numbers
    #[regex(r"\\s[1-5]?")]
    S,
    #[regex(r"\\sd[1-4]?")]
    Sd,
    #[regex(r"\\imt[1-3]?")]
    Imt,
    #[regex(r"\\is[1-2]?")]
    Is,
    #[regex(r"\\iq[1-3]?")]
    Iq,
    #[regex(r"\\ili[1-2]?")]
    Ili,
    #[regex(r"\\io[1-4]?")]
    Io,
    #[regex(r"\\imte[1-2]?")]
    Imte,
    #[regex(r"\\mt[1-4]?")]
    Mt,
    #[regex(r"\\mte[1-2]?")]
    Mte,
    #[regex(r"\\ms[1-3]?")]
    Ms,
    #[regex(r"\\pi[1-3]?")]
    Pi,
    #[regex(r"\\mi[1-3]?")]
    Mi,
    #[regex(r"\\q[1-4]?")]
    Q,
    #[regex(r"\\qm[1-3]?")]
    Qm,
    #[regex(r"\\li[1-4]?")]
    Li,
    #[regex(r"\\lim[1-4]?")]
    Lim,
    #[regex(r"\\toc[1-3]?")]
    Toc,
    #[regex(r"\\toca[1-3]?")]
    Toca,

    // --- 4. Character Style Markers (End markers first) ---
    #[regex(r"\\\+?addpn\*")]
    AddpnEnd,
    #[regex(r"\\\+?bdit\*")]
    BditEnd,
    #[regex(r"\\\+?add\*")]
    AddEnd,
    #[regex(r"\\\+?bk\*")]
    BkEnd,
    #[regex(r"\\\+?dc\*")]
    DcEnd,
    #[regex(r"\\\+?em\*")]
    EmEnd,
    #[regex(r"\\\+?jmp\*")]
    JmpEnd,
    #[regex(r"\\\+?k\*")]
    KEnd,
    #[regex(r"\\\+?nd\*")]
    NdEnd,
    #[regex(r"\\\+?ord\*")]
    OrdEnd,
    #[regex(r"\\\+?pn\*")]
    PnEnd,
    #[regex(r"\\\+?png\*")]
    PngEnd,
    #[regex(r"\\\+?qt\*")]
    QtEnd,
    #[regex(r"\\\+?rb\*")]
    RbEnd,
    #[regex(r"\\\+?rq\*")]
    RqEnd,
    #[regex(r"\\\+?ref\*")]
    RefEnd,
    #[regex(r"\\\+?sig\*")]
    SigEnd,
    #[regex(r"\\\+?sls\*")]
    SlsEnd,
    #[regex(r"\\\+?tl\*")]
    TlEnd,
    #[regex(r"\\\+?w\*")]
    WEnd,
    #[regex(r"\\\+?wa\*")]
    WaEnd,
    #[regex(r"\\\+?wg\*")]
    WgEnd,
    #[regex(r"\\\+?wh\*")]
    WhEnd,
    #[regex(r"\\\+?wj\*")]
    WjEnd,
    #[regex(r"\\\+?bd\*")]
    BdEnd,
    #[regex(r"\\\+?it\*")]
    ItEnd,
    #[regex(r"\\\+?no\*")]
    NoEnd,
    #[regex(r"\\\+?sc\*")]
    ScEnd,
    #[regex(r"\\\+?sup\*")]
    SupEnd,
    #[regex(r"\\\+?ior\*")]
    IorEnd,
    #[regex(r"\\\+?iqt\*")]
    IqtEnd,
    #[regex(r"\\\+?qas\*")]
    QasEnd,
    #[regex(r"\\\+?qs\*")]
    QsEnd,
    #[regex(r"\\\+?litl\*")]
    LitlEnd,
    #[regex(r"\\\+?lik\*")]
    LikEnd,
    #[regex(r"\\\+?liv\*")]
    LivEnd,
    #[regex(r"\\\+?fr\*")]
    FrEnd,
    #[regex(r"\\\+?fq\*")]
    FqEnd,
    #[regex(r"\\\+?fqa\*")]
    FqaEnd,
    #[regex(r"\\\+?fk\*")]
    FkEnd,
    #[regex(r"\\\+?ft\*")]
    FtEnd,
    #[regex(r"\\\+?fl\*")]
    FlEnd,
    #[regex(r"\\\+?fw\*")]
    FwEnd,
    #[regex(r"\\\+?fp\*")]
    FpEnd,
    #[regex(r"\\\+?fv\*")]
    FvEnd,
    #[regex(r"\\\+?fdc\*")]
    FdcEnd,
    #[regex(r"\\\+?fm\*")]
    FmEnd,
    #[regex(r"\\\+?xo\*")]
    XoEnd,
    #[regex(r"\\\+?xop\*")]
    XopEnd,
    #[regex(r"\\\+?xk\*")]
    XkEnd,
    #[regex(r"\\\+?xq\*")]
    XqEnd,
    #[regex(r"\\\+?xt\*")]
    XtEnd,
    #[regex(r"\\\+?xta\*")]
    XtaEnd,
    #[regex(r"\\\+?xot\*")]
    XotEnd,
    #[regex(r"\\\+?xnt\*")]
    XntEnd,
    #[regex(r"\\\+?xdc\*")]
    XdcEnd,
    #[regex(r"\\\+?fig\*")]
    FigEnd,
    #[regex(r"\\\+?cat\*")]
    CatEnd,
    #[token(r"\esbe")]
    EsbEnd, // Note: esb ends with 'e', not '*'
    #[regex(r"\\\+?f\*")]
    FEnd,
    #[regex(r"\\\+?fe\*")]
    FeEnd,
    #[regex(r"\\\+?ef\*")]
    EfEnd,
    #[regex(r"\\\+?x\*")]
    XEnd,
    #[regex(r"\\\+?ex\*")]
    ExEnd,
    #[token(r"\*")]
    ImplicitClose,

    // Character style start markers
    #[regex(r"\\z[\w-]+")]
    ZCustom,
    #[regex(r"\\\+?addpn")]
    Addpn,
    #[regex(r"\\\+?bdit")]
    Bdit,
    #[regex(r"\\\+?add")]
    Add,
    #[regex(r"\\\+?bk")]
    Bk,
    #[regex(r"\\\+?dc")]
    Dc,
    #[regex(r"\\\+?em")]
    Em,
    #[regex(r"\\\+?jmp")]
    Jmp,
    #[regex(r"\\\+?k")]
    K,
    #[regex(r"\\\+?nd")]
    Nd,
    #[regex(r"\\\+?ord")]
    Ord,
    #[regex(r"\\\+?pn")]
    Pn,
    #[regex(r"\\\+?png")]
    Png,
    #[regex(r"\\\+?qt")]
    Qt,
    #[regex(r"\\\+?rb")]
    Rb,
    #[regex(r"\\\+?rq")]
    Rq,
    #[regex(r"\\\+?ref")]
    Ref,
    #[regex(r"\\\+?sig")]
    Sig,
    #[regex(r"\\\+?sls")]
    Sls,
    #[regex(r"\\\+?tl")]
    Tl,
    #[regex(r"\\\+?w")]
    W,
    #[regex(r"\\\+?wa")]
    Wa,
    #[regex(r"\\\+?wg")]
    Wg,
    #[regex(r"\\\+?wh")]
    Wh,
    #[regex(r"\\\+?wj")]
    Wj,
    #[regex(r"\\\+?bd")]
    Bd,
    #[regex(r"\\\+?it")]
    It,
    #[regex(r"\\\+?no")]
    No,
    #[regex(r"\\\+?sc")]
    Sc,
    #[regex(r"\\\+?sup")]
    Sup,
    #[token(r"\pb")]
    Pb,
    #[token(r"//")]
    LineBreak,
    #[regex(r"\\\+?ior")]
    Ior,
    #[regex(r"\\\+?iqt")]
    Iqt,
    #[regex(r"\\\+?qas")]
    Qas,
    #[regex(r"\\\+?qs")]
    Qs,
    #[regex(r"\\\+?litl")]
    Litl,
    #[regex(r"\\\+?lik")]
    Lik,
    #[regex(r"\\\+?liv")]
    Liv,
    #[regex(r"\\\+?fr")]
    Fr,
    #[regex(r"\\\+?fq")]
    Fq,
    #[regex(r"\\\+?fqa")]
    Fqa,
    #[regex(r"\\\+?fk")]
    Fk,
    #[regex(r"\\\+?ft")]
    Ft,
    #[regex(r"\\\+?fl")]
    Fl,
    #[regex(r"\\\+?fw")]
    Fw,
    #[regex(r"\\\+?fp")]
    Fp,
    #[regex(r"\\\+?fv")]
    Fv,
    #[regex(r"\\\+?fdc")]
    Fdc,
    #[regex(r"\\\+?fm")]
    Fm,
    #[regex(r"\\\+?xo")]
    Xo,
    #[regex(r"\\\+?xop")]
    Xop,
    #[regex(r"\\\+?xk")]
    Xk,
    #[regex(r"\\\+?xq")]
    Xq,
    #[regex(r"\\\+?xt")]
    Xt,
    #[regex(r"\\\+?xta")]
    Xta,
    #[regex(r"\\\+?xot")]
    Xot,
    #[regex(r"\\\+?xnt")]
    Xnt,
    #[regex(r"\\\+?xdc")]
    Xdc,
    #[regex(r"\\\+?fig")]
    Fig,
    #[regex(r"\\\+?cat")]
    Cat,
    #[token(r"\esb")]
    Esb,
    #[regex(r"\\\+?f")]
    F,
    #[regex(r"\\\+?fe")]
    Fe,
    #[regex(r"\\\+?ef")]
    Ef,
    #[regex(r"\\\+?x")]
    X,
    #[regex(r"\\\+?ex")]
    Ex,

    // --- 5. Simple Paragraph/Document Markers (least specific) ---
    #[token(r"\id", id_callback)]
    Id,
    #[token(r"\usfm")]
    Usfm,
    #[token(r"\ide")]
    Ide,
    #[token(r"\sts")]
    Sts,
    #[token(r"\rem")]
    Rem,
    #[token(r"\h")]
    H,
    #[token(r"\ip")]
    Ip,
    #[token(r"\ipi")]
    Ipi,
    #[token(r"\im")]
    Im,
    #[token(r"\imi")]
    Imi,
    #[token(r"\ipq")]
    Ipq,
    #[token(r"\imq")]
    Imq,
    #[token(r"\ipr")]
    Ipr,
    #[token(r"\ib")]
    Ib,
    #[token(r"\iot")]
    Iot,
    #[token(r"\iex")]
    Iex,
    #[token(r"\ie")]
    Ie,
    #[token(r"\cl")]
    Cl,
    #[token(r"\cd")]
    Cd,
    #[token(r"\mr")]
    Mr,
    #[token(r"\sr")]
    Sr,
    #[token(r"\r")]
    R,
    #[token(r"\d")]
    D,
    #[token(r"\sp")]
    Sp,
    #[token(r"\p")]
    P,
    #[token(r"\m")]
    M,
    #[token(r"\po")]
    Po,
    #[token(r"\cls")]
    Cls,
    #[token(r"\pr")]
    Pr,
    #[token(r"\pc")]
    Pc,
    #[token(r"\pm")]
    Pm,
    #[token(r"\pmo")]
    Pmo,
    #[token(r"\pmc")]
    Pmc,
    #[token(r"\pmr")]
    Pmr,
    #[token(r"\lit")]
    Lit,
    #[token(r"\nb")]
    Nb,
    #[token(r"\b")]
    B,
    #[token(r"\qr")]
    Qr,
    #[token(r"\qc")]
    Qc,
    #[token(r"\qa")]
    Qa,
    #[token(r"\qd")]
    Qd,
    #[token(r"\lh")]
    Lh,
    #[token(r"\lf")]
    Lf,
    #[token(r"\tr")]
    Tr,
    #[token(r"\c")]
    C,
    #[token(r"\ca")]
    Ca,
    #[token(r"\cp")]
    Cp,
    #[token(r"\v")]
    V,
    #[token(r"\va")]
    Va,
    #[token(r"\vp")]
    Vp,

    // --- 6. Data Tokens ---
    // The `verseRange` from moo is now just a Number in the verseRange state
    // todo why do you have to put leading ws? It should be capture in ws tokens;
    #[regex(
        r"[ \t]*[1-9][0-9]*[\p{L}\p{Mn}]*(?:[,\-][0-9]+[\p{L}\p{Mn}]*)*",
        priority = 10
    )]
    VerseRange,
    #[regex(r"[A-Z]{3}", priority = 2)]
    BookCode,

    // --- 7. Content Fallback ---
    #[regex(r"[^\s\\|][^\\|]*", priority = 1)]
    Text,
}

// This is a “sub-lexer” for inside the \id context
#[derive(Logos, Debug, PartialEq, Clone)]
pub enum IdExtras {
    #[regex(r"[A-Z1-9]{3}")]
    BookCode,
    #[regex(r"[ \t]+")]
    Ws,
}

fn id_callback(lex: &mut logos::Lexer<TokenKind>) -> Option<()> {
    // Morph into sub-lexer for the ID extras
    let mut sub_lexer = lex.clone().morph::<IdExtras>();

    while let Some(token) = sub_lexer.next() {
        match token {
            Ok(IdExtras::BookCode) => {
                // Here we could push a BookCode token somewhere in your parser
                // Or just let the main lexer pick it up naturally
                break; // stop after finding the first BookCode
            }
            _ => {}
        }
    }

    // Morph back to main lexer so it continues lexing after what sub-lexer consumed
    *lex = sub_lexer.morph();

    Some(())
}

static TOKENS_EXPECTING_CLOSE: Lazy<HashSet<TokenKind>> = Lazy::new(|| {
    HashSet::from([
        // Character style markers (alphabetical order)
        TokenKind::Add,
        TokenKind::Addpn,
        TokenKind::Bd,
        TokenKind::Bdit,
        TokenKind::Bk,
        TokenKind::Cat,
        TokenKind::Dc,
        TokenKind::Ef,
        TokenKind::Em,
        TokenKind::Esb,
        TokenKind::Ex,
        TokenKind::F,
        TokenKind::Fdc,
        TokenKind::Fe,
        TokenKind::Fig,
        TokenKind::Fk,
        TokenKind::Fl,
        TokenKind::Fm,
        TokenKind::Fp,
        TokenKind::Fq,
        TokenKind::Fqa,
        TokenKind::Fr,
        TokenKind::Ft,
        TokenKind::Fv,
        TokenKind::Fw,
        TokenKind::Ior,
        TokenKind::Iqt,
        TokenKind::It,
        TokenKind::Jmp,
        TokenKind::K,
        TokenKind::Lik,
        TokenKind::Litl,
        TokenKind::Liv,
        TokenKind::Nd,
        TokenKind::No,
        TokenKind::Ord,
        TokenKind::Pn,
        TokenKind::Png,
        TokenKind::Qas,
        TokenKind::Qs,
        TokenKind::Qt,
        TokenKind::Rb,
        TokenKind::Ref,
        TokenKind::Rq,
        TokenKind::Sc,
        TokenKind::Sig,
        TokenKind::Sls,
        TokenKind::Sup,
        TokenKind::Tl,
        TokenKind::W,
        TokenKind::Wa,
        TokenKind::Wg,
        TokenKind::Wh,
        TokenKind::Wj,
        TokenKind::X,
        TokenKind::Xdc,
        TokenKind::Xk,
        TokenKind::Xnt,
        TokenKind::Xo,
        TokenKind::Xop,
        TokenKind::Xot,
        TokenKind::Xq,
        TokenKind::Xt,
        TokenKind::Xta,
        // Custom Z markers
        TokenKind::ZCustom,
        // Milestone markers
        TokenKind::QtMilestoneStart,
        TokenKind::TsMilestoneStart,
        // Special verse markers
        TokenKind::Ca,
        TokenKind::Va,
        TokenKind::Vp,
    ])
});
static MARKER_LEVEL_RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"(\d+)").unwrap());
static ATTRIBUTE_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r#"^([a-zA-Z0-9\-_]+)="([^"]*)"$"#).unwrap());

static CHAPTER_RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"^(\d+)").unwrap());

// Token is now so small, it can be Copy
#[derive(Debug, Clone, Copy)]
pub struct Token<'i> {
    pub kind: TokenKind,
    pub text: &'i str,
    pub span: (usize, usize),
}

// ParsedToken borrows from the input and has no redundant info
#[derive(Debug, PartialEq, Clone, Serialize)] // Removed Clone, we'll avoid it
pub struct ParsedToken<'i> {
    pub kind: TokenKind, // Store the enum directly
    pub text: &'i str,
    pub span: (usize, usize),
    pub level: Option<&'i str>, // Borrow the level number
    pub content: Vec<ParsedToken<'i>>,
    pub attributes: HashMap<&'i str, &'i str>, // Borrow attributes too
}

// The final result also needs the lifetime
#[derive(Debug, Clone, Serialize)]
pub struct ParsedUSFM<'i> {
    pub intro: Vec<ParsedToken<'i>>,
    pub chapters: HashMap<u32, Vec<ParsedToken<'i>>>,
}
#[derive(Serialize, Clone)]
pub struct OwnedParsedUSFM {
    pub intro: Vec<OwnedParsedToken>,
    pub chapters: HashMap<u32, Vec<OwnedParsedToken>>,
}

#[derive(Serialize, Clone)]
pub struct OwnedParsedToken {
    pub kind: TokenKind, // Store the enum directly
    pub text: String,
    pub span: (usize, usize),
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<String>, // Borrow the level number
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<OwnedParsedToken>,
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    pub attributes: HashMap<String, String>, // Borrow attributes too
}
impl<'i> From<ParsedUSFM<'i>> for OwnedParsedUSFM {
    fn from(borrowed: ParsedUSFM<'i>) -> Self {
        OwnedParsedUSFM {
            intro: borrowed.intro.into_iter().map(|t| t.into()).collect(),
            chapters: borrowed
                .chapters
                .into_iter()
                .map(|(k, v)| (k, v.into_iter().map(|t| t.into()).collect()))
                .collect(),
        }
    }
}

impl<'i> From<ParsedToken<'i>> for OwnedParsedToken {
    fn from(b: ParsedToken<'i>) -> Self {
        OwnedParsedToken {
            kind: b.kind,
            span: b.span,
            text: b.text.to_string(),
            level: b.level.map(|s| s.to_string()),
            content: b.content.into_iter().map(|t| t.into()).collect(),
            attributes: b
                .attributes
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
        }
    }
}

// fn push_whitespace_onto_prev_token(tokens: &mut Vec<Token>) {

//     if tokens.len() < 2 {
//         return; // Nothing to merge
//     }

//     let mut write_idx = 0;
//     for read_idx in 0..tokens.len() {
//         // Condition: Can we merge the token at `read_idx` into the one at `write_idx - 1`?
//         if write_idx > 0 && matches!(tokens[read_idx].kind, TokenKind::Ws | TokenKind::Nl) {
//             // This is the key part!
//             // We split the vector right before the token we want to read from.
//             let (head, tail) = tokens.split_at_mut(read_idx);

//             // `head` contains everything up to `read_idx`. The token we want
//             // to modify is the last one in `head`.
//             let prev_token = &mut head[write_idx - 1];

//             // `tail` contains everything from `read_idx` onwards. The token
//             // we are reading from is the first one in `tail`.
//             let current_token_text = &tail[0].text;

//             // Now we can merge, because the borrow checker knows `prev_token`
//             // and `current_token_text` come from non-overlapping slices.
//             prev_token.text.push_str(current_token_text);
//         } else {
//             // This token is not whitespace, or it's the first token.
//             // Move it to the write position if necessary.
//             if write_idx != read_idx {
//                 tokens.swap(write_idx, read_idx);
//             }
//             write_idx += 1;
//         }
//     }

//     // Remove the now-merged whitespace tokens from the end of the vector.
//     tokens.truncate(write_idx);
// }

fn parse_attribute_pair<'i>(attr_text: &'i str) -> Option<(&'i str, &'i str)> {
    // PERF: Captures now return borrowed &'i str, no String allocation.
    ATTRIBUTE_RE.captures(attr_text).and_then(|caps| {
        let k = caps.get(1)?.as_str();
        let v = caps.get(2)?.as_str();
        Some((k, v))
    })
}

fn create_parsed_token<'i>(token: &Token<'i>) -> ParsedToken<'i> {
    // PERF: No more `format!`, no String clones.
    let level = if is_marker(token.text) {
        MARKER_LEVEL_RE
            .captures(token.text)
            .and_then(|caps| caps.get(1).map(|m| m.as_str()))
    } else {
        None
    };

    ParsedToken {
        kind: token.kind,
        text: token.text,
        span: token.span,
        level,
        content: vec![],
        attributes: HashMap::new(),
    }
}

fn parse_token_stream<'i>(tokens: &[Token<'i>]) -> Vec<ParsedToken<'i>> {
    let mut result: Vec<ParsedToken<'i>> = Vec::new();

    // PERF: The stack now stores indices, not references. This is the key to
    // satisfying the borrow checker. It represents the path to the current parent.
    // e.g., `[0, 2]` means `result[0].content[2]`
    let mut stack: Vec<usize> = Vec::new();

    for token in tokens {
        // --- Handle Attribute Tokens ---
        // Attributes apply to the most recently added node at the current depth.
        if token.kind == TokenKind::AttrPair {
            // 1. Get a mutable reference to the current parent's content Vec.
            let mut current_level = &mut result;
            for &index in &stack {
                current_level = &mut current_level[index].content;
            }

            // 2. Modify the last node in that Vec.
            if let Some(last_node) = current_level.last_mut() {
                if is_marker(last_node.text) {
                    if let Some((k, v)) = parse_attribute_pair(token.text) {
                        last_node.attributes.insert(k, v);
                    }
                }
            }
            continue;
        }

        // --- Handle Closing Markers ---
        if is_end_marker(token.kind) {
            // A closing tag just means we go up one level in the hierarchy.
            stack.pop();
            continue;
        }

        // --- Handle Opening / Standalone Tokens ---
        let parsed_token = create_parsed_token(token);

        // 1. Get a mutable reference to the parent's content Vec by walking the path.
        // This is the "get current" step.
        let parent_content = {
            let mut current = &mut result;
            for &index in &stack {
                // Get the node at the index, then get a reference to its content vec
                current = &mut current[index].content;
            }
            current
        };

        // 2. Move the new token into the parent's content.
        parent_content.push(parsed_token);

        // 3. If the token we just added is a container, update the path.
        // The new path is the old path plus the index of the element we just added.
        if TOKENS_EXPECTING_CLOSE.contains(&token.kind) {
            let new_index = parent_content.len() - 1;
            stack.push(new_index);
        }
    }

    result
}

pub fn is_marker(text: &str) -> bool {
    text.starts_with('\\')
}

// is_end_marker now takes a TokenKind directly
pub fn is_end_marker(kind: TokenKind) -> bool {
    matches!(
        kind,
        TokenKind::ImplicitClose
            | TokenKind::QtMilestoneEnd
            | TokenKind::TsMilestoneEnd
            | TokenKind::ZMilestoneEnd
            | TokenKind::AddEnd
            | TokenKind::AddpnEnd
            | TokenKind::BdEnd
            | TokenKind::BditEnd
            | TokenKind::BkEnd
            | TokenKind::CatEnd
            | TokenKind::DcEnd
            | TokenKind::EfEnd
            | TokenKind::EmEnd
            | TokenKind::EsbEnd
            | TokenKind::ExEnd
            | TokenKind::FEnd
            | TokenKind::FdcEnd
            | TokenKind::FeEnd
            | TokenKind::FigEnd
            | TokenKind::FkEnd
            | TokenKind::FlEnd
            | TokenKind::FmEnd
            | TokenKind::FpEnd
            | TokenKind::FqEnd
            | TokenKind::FqaEnd
            | TokenKind::FrEnd
            | TokenKind::FtEnd
            | TokenKind::FvEnd
            | TokenKind::FwEnd
            | TokenKind::IorEnd
            | TokenKind::IqtEnd
            | TokenKind::ItEnd
            | TokenKind::JmpEnd
            | TokenKind::KEnd
            | TokenKind::LikEnd
            | TokenKind::LitlEnd
            | TokenKind::LivEnd
            | TokenKind::NdEnd
            | TokenKind::NoEnd
            | TokenKind::OrdEnd
            | TokenKind::PnEnd
            | TokenKind::PngEnd
            | TokenKind::QasEnd
            | TokenKind::QsEnd
            | TokenKind::QtEnd
            | TokenKind::RbEnd
            | TokenKind::RefEnd
            | TokenKind::RqEnd
            | TokenKind::ScEnd
            | TokenKind::SigEnd
            | TokenKind::SlsEnd
            | TokenKind::SupEnd
            | TokenKind::TlEnd
            | TokenKind::WEnd
            | TokenKind::WaEnd
            | TokenKind::WgEnd
            | TokenKind::WhEnd
            | TokenKind::WjEnd
            | TokenKind::XEnd
            | TokenKind::XdcEnd
            | TokenKind::XkEnd
            | TokenKind::XntEnd
            | TokenKind::XoEnd
            | TokenKind::XopEnd
            | TokenKind::XotEnd
            | TokenKind::XqEnd
            | TokenKind::XtEnd
            | TokenKind::XtaEnd
    )
}

// PERF: The function now works with the borrowed `ParsedToken<'i>`
pub fn organize_by_chapters<'i>(tokens: Vec<ParsedToken<'i>>) -> ParsedUSFM<'i> {
    // 1. PRE-COMPUTATION PASS: Find the start index of every chapter marker.
    // We iterate once to find all `TokenKind::C` and store their positions.
    let chapter_start_indices: Vec<usize> = tokens
        .iter()
        .enumerate()
        .filter(|(_i, token)| token.kind == TokenKind::C)
        .map(|(i, _token)| i)
        .collect();

    // If there are no chapter markers at all, the entire document is the intro.
    if chapter_start_indices.is_empty() {
        return ParsedUSFM {
            intro: tokens, // We can move the whole vector, no clone needed.
            chapters: HashMap::new(),
        };
    }

    // --- SLICING AND ORGANIZATION ---

    // 2. The intro is everything from the beginning up to the first chapter marker.
    let first_chapter_index = chapter_start_indices[0];
    let intro = tokens[0..first_chapter_index].to_vec(); // .to_vec() creates an owned copy

    // 3. Create chapter chunks using the pre-computed indices.
    let mut chapters = HashMap::new();

    // Create an iterator that gives us the start and end index for each chapter's slice.
    // We chain the list of start indices with the total length of the token vec,
    // then use `.windows(2)` to create pairs like `[start1, start2]`, `[start2, start3]`, etc.
    let ranges = chapter_start_indices
        .iter()
        .map(|&i| i) // Convert `&usize` to `usize`
        .chain(std::iter::once(tokens.len()));

    for window in ranges.collect::<Vec<_>>().windows(2) {
        let start_index = window[0];
        let end_index = window[1];

        // Get the slice of tokens for the current chapter.
        let chapter_tokens = &tokens[start_index..end_index];

        // The first token is `\c`. The token *after* it should contain the number.
        // A robust parser would validate this structure carefully.
        if chapter_tokens.len() > 1 {
            let number_token = &chapter_tokens[1];
            // Trim whitespace and parse the text to a u32 for the HashMap key.
            if let Ok(chapter_num) = number_token.text.trim().parse::<u32>() {
                // Insert an owned copy of the slice into the map.
                chapters.insert(chapter_num, chapter_tokens.to_vec());
            } else {
                // Handle the case where a `\c` is not followed by a valid number.
                // For now, we'll just skip this malformed chapter.
                println!("Warning: Malformed chapter marker at index {}", start_index);
            }
        }
    }

    ParsedUSFM { intro, chapters }
}

pub fn parse_usfm(input: &str) -> ParsedUSFM {
    let lexer = TokenKind::lexer(input);
    let tokens: Vec<Token> = lexer
        .spanned()
        .filter_map(|(res_kind, span)| {
            // res_kind: Result<TokenKind, ()>
            let span = (span.start, span.end);
            if let Ok(kind) = res_kind {
                Some(Token {
                    text: &input[span.0..span.1],
                    span,
                    kind,
                })
            } else {
                None // or handle error in some way
            }
        })
        .collect();

    // push_whitespace_onto_prev_token(&mut tokens);

    let parsed_tokens = parse_token_stream(&tokens);
    let organized = organize_by_chapters(parsed_tokens);

    organized
}
