name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS arm64
          - os: macos-latest
            args: '--target aarch64-apple-darwin'
            mobile: false

          # macOS x64
          - os: macos-latest
            args: '--target x86_64-apple-darwin'
            mobile: false

          # Windows
          - os: windows-latest
            args: ''
            mobile: false

          # Linux desktop
          - os: ubuntu-22.04
            args: ''
            mobile: false

          # Android build
          - os: ubuntu-22.04
            args: ''
            mobile: android

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf


      - name: Install dependencies
        run: pnpm install

      - name: Initialize Android project if missing
        if: matrix.os == 'ubuntu-22.04'
        run: |
          if [ ! -d src/tauri/gen/android ]; then
            pnpm tauri android init -y
          fi

      - name: Build + Release
        uses: tauri-apps/tauri-action@mobile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile }}
